name: Build and Deploy

on:
  push:
    branches:
      - master
  release:
    types: [ published ]

defaults:
  run:
    shell: bash

jobs:
  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          push: startsWith(github.ref, 'refs/tags/')
          tags: daniel/wordle-dash-app:${{ env.RELEASE_VERSION }}

  update:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: SSH to DO instance, stop existing app and spin up new app
        run: echo "Hello World"