name: Build and Deploy

on:
  push:
    branches:
      - master
  release:
    types: [ published ]

defaults:
  run:
    shell: bash

env:
  IMAGE_NAME: danielbok/wordle-dash-app

jobs:
  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ env.IMAGE_NAME }}

  update:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: SSH to DO instance, stop existing app and spin up new app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_PRIVATE_KEY }}
          script_stop: true  # stops after first failure
          script: |
            docker container kill wordle
            docker container prune -f
            docker image pull ${{ env.IMAGE_NAME }}
            docker image prune -f
            docker container run -p 8080:8080 --name wordle --rm -d ${{ env.IMAGE_NAME }}
